--- # Sample Ansible playbook that creates a file and echos a message
- name: create file and echo text
  hosts: slaves
  remote_user: ec2-user
  become: true
  tasks:
  - name: create hello.txt file
    file: path=/home/ec2-user/hello.txt state=touch
  - name: change hello.txt permissions
    file: path=/home/ec2-user/hello.txt owner=ec2-user group=ec2-user mode=0400
  - name: echo an arbitrary message to hello.txt
    shell: echo "hello from ansible" >> /home/ec2-user/hello.txt
